# All available configuration options are found at
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
#
# Commented options are used by default in the current version of Rust
# Last Updated: rustfmt 1.4.11

# binop_separator = "Front"
# blank_lines_lower_bound = 0
# brace_styler = "SameLineWhere"
# color = "Auto"
# combine_control_expr = true
# comment_width = 80
condense_wildcard_suffixes = true
# control_brace_style = "AlwaysSameLine"
# disable_all_formatting = false
edition = "2018"
# empty_item_single_liner = true
# enum_discrim_align_threshold = 0
error_on_line_overflow = true
error_on_unformatted = true
# fn_args_layout = "Tall"
fn_single_line = true
# force_explicit_abi = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
# format_macro_bodies = true
format_strings = true
# hard_tabs = false
# hide_parse_errors = false
# ignore = []
# imports_indent = "Block"
imports_layout = "HorizontalVertical"
# indent_style = "Block"
# inline_attribute_width = 0
# license_template_path = ""
# match_arm_blocks = true
match_block_trailing_comma = true
# max_width = 100
# merge_derives = true
merge_imports = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
# overflow_delimited_expr = false
# remove_nested_parens = true
reorder_impl_items = true
# reorder_imports = true
# reorder_modules = true
report_fixme = "Unnumbered"
report_todo = "Unnumbered"
# required_version = $CARGO_PKG_VERSION
# skip_children = false
# space_after_colon = true
# space_before_colon = false
# spaces_around_ranges = false
# struct_field_align_threshold = 0
# struct_lit_single_line = true
# tab_spaces = 4
# trailing_comma = "Vertical"
# trailing_semicolon = true
# type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = true
# use_small_heuristics = "Default"
use_try_shorthand = true
# version = "One"
# where_single_line = false
wrap_comments = true
